/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Administrator
 */
public class PnlArchive extends javax.swing.JPanel {

    ConnectDB connection=null;
    
    public PnlArchive(ConnectDB connection) {
        initComponents();
        this.setSize(714, 609);
        
        
        this.connection=connection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnInvoice = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnUsers = new javax.swing.JButton();

        setLayout(null);

        pnlMain.setBackground(new java.awt.Color(254, 250, 246));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-backup-100.png"))); // NOI18N
        jLabel4.setText("Welcome To Archive");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setIconTextGap(10);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(258, 258, 258))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel4)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        add(pnlMain);
        pnlMain.setBounds(0, 90, 710, 470);

        btnInvoice.setBackground(new java.awt.Color(218, 192, 163));
        btnInvoice.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btnInvoice.setText("INVOICE");
        btnInvoice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 44, 87), 3, true));
        btnInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceActionPerformed(evt);
            }
        });
        add(btnInvoice);
        btnInvoice.setBounds(480, 20, 230, 70);

        jButton2.setBackground(new java.awt.Color(218, 192, 163));
        jButton2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton2.setText("MENU");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 44, 87), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(0, 20, 230, 70);

        btnUsers.setBackground(new java.awt.Color(218, 192, 163));
        btnUsers.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btnUsers.setText("USERS");
        btnUsers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 44, 87), 3, true));
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });
        add(btnUsers);
        btnUsers.setBounds(230, 20, 250, 70);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.pnlMain.removeAll();
        this.pnlMain.add(new PnlArcMenu(connection));
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        this.pnlMain.removeAll();
        this.pnlMain.add(new PnlArcUsers(connection));
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceActionPerformed
        this.pnlMain.removeAll();
        this.pnlMain.add(new PnlArcInvoice(connection));
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnInvoiceActionPerformed

    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInvoice;
    private javax.swing.JButton btnUsers;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
