
import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Administrator
 */
public class PnlArcMenu extends javax.swing.JPanel {

    protected ConnectDB connection = null;
    protected DefaultTableModel tblModel;
    
    public PnlArcMenu(ConnectDB connection) {
        initComponents();
        this.setSize(710, 470);
        
        this.connection=connection;
        this.tblModel = (DefaultTableModel) tblArcMenu.getModel();
        
        
        //design sa table header wala kasi sa design tab
        this.tblArcMenu.getTableHeader().setFont(new Font("Sogoe UI", Font.BOLD, 16));  
        this.tblArcMenu.getTableHeader().setBackground(new Color(0xEADBC8));
        this.tblArcMenu.getTableHeader().setBorder(BorderFactory.createEmptyBorder());
        
        this.tblArcMenu.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.tblArcMenu.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
           
            public void valueChanged(ListSelectionEvent e) {
                
                
                
                // Check kung marami nakaselect na row
                if (tblArcMenu.getSelectedRowCount() > 1) {
                   //nililimit sa isa lang yung pagselect ng rows
                    int[] selectedRows = tblArcMenu.getSelectedRows();
                    tblArcMenu.getSelectionModel().setSelectionInterval(selectedRows[0], selectedRows[0]);
                }
            }
        });
        
        this.displayArcMenuTbl();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblArcMenu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnRetrieve = new javax.swing.JButton();

        setBackground(new java.awt.Color(254, 250, 246));

        jScrollPane1.setBackground(new java.awt.Color(254, 250, 246));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 250, 246)));

        tblArcMenu.setAutoCreateRowSorter(true);
        tblArcMenu.setBackground(new java.awt.Color(254, 250, 246));
        tblArcMenu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tblArcMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Food ID", "Food Name", "Price", "Food Pic"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblArcMenu.setFillsViewportHeight(true);
        tblArcMenu.setGridColor(new java.awt.Color(254, 250, 246));
        tblArcMenu.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tblArcMenu.setRowHeight(25);
        tblArcMenu.setSelectionBackground(new java.awt.Color(16, 44, 87));
        tblArcMenu.setSelectionForeground(new java.awt.Color(254, 250, 246));
        jScrollPane1.setViewportView(tblArcMenu);
        if (tblArcMenu.getColumnModel().getColumnCount() > 0) {
            tblArcMenu.getColumnModel().getColumn(0).setResizable(false);
            tblArcMenu.getColumnModel().getColumn(0).setPreferredWidth(3);
            tblArcMenu.getColumnModel().getColumn(0).setCellRenderer(new DefaultTableCellRenderer() {
                {
                    setHorizontalAlignment(SwingConstants.CENTER);
                }
            });
            tblArcMenu.getColumnModel().getColumn(1).setResizable(false);
            tblArcMenu.getColumnModel().getColumn(2).setResizable(false);
            tblArcMenu.getColumnModel().getColumn(2).setPreferredWidth(7);
            tblArcMenu.getColumnModel().getColumn(2).setCellRenderer(new DefaultTableCellRenderer() {
                {
                    setHorizontalAlignment(SwingConstants.CENTER);
                }
            });
            tblArcMenu.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("MENU");

        btnRetrieve.setBackground(new java.awt.Color(218, 192, 163));
        btnRetrieve.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRetrieve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-refresh-document-from-company-digital-file-system-48.png"))); // NOI18N
        btnRetrieve.setText("Retrieve");
        btnRetrieve.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 44, 87), 2, true));
        btnRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrieveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(btnRetrieve, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnRetrieve, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrieveActionPerformed
        int selectedRow = tblArcMenu.getSelectedRow();
                
                if(selectedRow==-1){
                    JOptionPane.showMessageDialog(this, "Please select a row");
                    return;
                }
        
        int response = JOptionPane.showConfirmDialog(this,"Are you sure want to retrieve this item?",
                        "Confirmation",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE );
        switch(response){
            case 0:
                
                
                    String fID=""+tblArcMenu.getValueAt(selectedRow, 0);
                    String fName=""+tblArcMenu.getValueAt(selectedRow, 1);
                    String fPrice=""+tblArcMenu.getValueAt(selectedRow, 2);
                    String fPic=""+tblArcMenu.getValueAt(selectedRow, 3);
                    
                    try{
                        //lagay sa menu table then alisin sa archive
                        String command="INSERT INTO MENU (food_id, food_name, food_price, food_pic) VALUES(?,?,?,?)";
                        PreparedStatement ps = connection.con.prepareStatement(command);
                        ps.setInt(1, Integer.parseInt(fID));
                        ps.setString(2, fName);
                        ps.setInt(3, Integer.parseInt(fPrice));
                        ps.setString(4, fPic);

                        ps.executeUpdate();
                        
                        
                        //delete sa archive
                        ps = connection.con.prepareStatement("DELETE FROM ARCMENU WHERE food_id=?");
                        ps.setInt(1, Integer.parseInt(fID));
                        ps.executeUpdate();
                        
                        JOptionPane.showMessageDialog(this, "Item Successfully Retrieve");
                        
                        this.displayArcMenuTbl(); 
                        
                        ps.close();
                        
                        
                    }catch(Exception e){      
                        System.out.println(e.getMessage());
                    }
                
                
                
                break;
                
            case 1:
                
                break;
        }
    }//GEN-LAST:event_btnRetrieveActionPerformed
    
    
    
    //display mga laman ng table
    public void displayArcMenuTbl(){
        if(tblModel.getRowCount()>0){
            for(int i =tblModel.getRowCount()-1; i>=0; i--){
                tblModel.removeRow(i);
            }
        }
        
        
        String command="SELECT * FROM ARCMENU ORDER BY FOOD_ID";
        ResultSet results=connection.getResult(command);
        
        
        try{
            while(results.next()){
                String fID = results.getString("food_id");
                String fName = results.getString("food_name");
                String fPrice= results.getString("food_price");
                String fPic = results.getString("food_pic");
                
                String newRow[]={fID, fName, fPrice, fPic};
                
                tblModel.addRow(newRow);
                
            }
            results.close();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetrieve;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblArcMenu;
    // End of variables declaration//GEN-END:variables
}
